#define REDIS_GIT_SHA1 "0"
#define REDIS_GIT_DIRTY "0"
#define REDIS_BUILD_ID "valkey-wasm"
#include "version.h"
#define REDIS_BUILD_ID_RAW SERVER_NAME VALKEY_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
